#docker save <my_image> | ssh -C user@my.remote.host.com docker load
#
#https://stackoverflow.com/questions/31575546/docker-image-push-over-ssh-distributed

name: "Push Image to Ubuntu Server"
description: "Push Image to Ubuntu Server"

inputs:
  IMAGE_TAG:
    required: true
    description: "Docker image tag"
  HOST:
    required: true
    description: "Ubuntu Server Host"
  USERNAME:
    required: true
    description: "Ubuntu Server Username"
  PASSWORD:
    required: true
    description: "Ubuntu Server Password"
  PORT:
    required: true
    description: "Ubuntu Server Host"
  PUBLIC_KEY:
    required: true
    description: "Ubuntu Server Public Key"
  PRIVATE_KEY:
    required: true
    description: "Ubuntu Server Private Key"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.HOST }}
        username: ${{ inputs.USERNAME }}
        password: ${{ inputs.PASSWORD }}
        port: ${{ inputs.PORT }}
        script: |
          cd projects
          git clone git@github.com:WilsonGodoi/gym.git
          cd gym
          git fetch
          git checkout ${{ github.ref_name }}
          ./mvnw package
          docker-compose -f docker-compose.yaml up -d --build
          cd ..
          rm -rf gym-ui/

    - name: Push Image
      shell: bash
      run: |
        echo ${{ inputs.IMAGE_TAG }}
        mkdir backup
        docker save -o backup/${{ inputs.IMAGE_TAG }}.tar ${{ inputs.IMAGE_TAG }}
        cd backup
        ls
    # scp -P ${{ inputs.PORT }} ${{ inputs.IMAGE_TAG }}.tar ${{ inputs.USERNAME }}@${{ inputs.HOST }}:~/
    # docker save ${{ inputs.IMAGE_TAG }}  docker load

    # - name: copy file via ssh password
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ inputs.HOST }}
    #     username: ${{ inputs.USERNAME }}
    #     password: ${{ inputs.PASSWORD }}
    #     port: ${{ inputs.PORT }}
    #     source: "backup/${{ inputs.IMAGE_TAG }}.tar"
    #     target: ~/projects
