version: "3.9"

services:
  gym-api:
    container_name: gym-api
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    depends_on:
      - gym-db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://gym-db:5432/gym_db
      - QUARKUS_DATASOURCE_USERNAME=user_dummy
      - QUARKUS_DATASOURCE_PASSWORD=password_dummy
    ports:
      - "8080:8080"
    restart: always
  gym-db:
    container_name: gym-db
    image: postgres:16.2-bullseye
    environment:
      - POSTGRES_USER=user_dummy
      - POSTGRES_PASSWORD=password_dummy
      - POSTGRES_DB=gym_db
    ports:
      - "5432:5432"