version: "3.9"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres:16.2-bullseye
    environment:
      - POSTGRES_USER=user_dummy
      - POSTGRES_PASSWORD=password_dummy
      - POSTGRES_DB=gym_db
    ports:
      - "5432:5432"