create table users
(
    id        bigint generated by default as identity,
    email     varchar(255),
    password  varchar(255),
    firstName varchar(255),
    lastName  varchar(255),
    primary key (id),
    unique (email)
);
