CREATE TABLE exercise
(
    id    bigint generated by default as identity,
    email VARCHAR(255) NOT NULL,
    exerciseGroupType VARCHAR(15) NOT NULL,
    FOREIGN KEY (email) REFERENCES users (email),
    FOREIGN KEY (exerciseGroupType) REFERENCES exercise_group_type (type)
);